In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
df = pd.read_csv("/content/drive/MyDrive/ML Project/genres/features_3_sec.csv")

In [ ]:
df.head()

,filename,length,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,spectral_centroid_mean,spectral_centroid_var,spectral_bandwidth_mean,spectral_bandwidth_var,...,mfcc16_var,mfcc17_mean,mfcc17_var,mfcc18_mean,mfcc18_var,mfcc19_mean,mfcc19_var,mfcc20_mean,mfcc20_var,label
0,blues.00000.0.wav,66149,0.335406,0.091048,0.130405,0.003521,1773.065032,167541.630869,1972.744388,117335.771563,...,39.687145,-3.241280,36.488243,0.722209,38.099152,-5.050335,33.618073,-0.243027,43.771767,blues
1,blues.00000.1.wav,66149,0.343065,0.086147,0.112699,0.001450,1816.693777,90525.690866,2010.051501,65671.875673,...,64.748276,-6.055294,40.677654,0.159015,51.264091,-2.837699,97.030830,5.784063,59.943081,blues
2,blues.00000.2.wav,66149,0.346815,0.092243,0.132003,0.004620,1788.539719,111407.437613,2084.565132,75124.921716,...,67.336563,-1.768610,28.348579,2.378768,45.717648,-1.938424,53.050835,2.517375,33.105122,blues
3,blues.00000.3.wav,66149,0.363639,0.086856,0.132565,0.002448,1655.289045,111952.284517,1960.039988,82913.639269,...,47.739452,-3.841155,28.337118,1.218588,34.770935,-3.580352,50.836224,3.630866,32.023678,blues
4,blues.00000.4.wav,66149,0.335579,0.088129,0.143289,0.001701,1630.656199,79667.267654,1948.503884,60204.020268,...,30.336359,0.664582,45.880913,1.689446,51.363583,-3.392489,26.738789,0.536961,29.146694,blues

#Checking for duplicates

In [ ]:
boolean = df.duplicated().sum()
print(boolean)

0

In [ ]:
df.duplicated().sum()
df.drop_duplicates
df.isnull().sum()

filename                   0
length                     0
chroma_stft_mean           0
chroma_stft_var            0
rms_mean                   0
rms_var                    0
spectral_centroid_mean     0
spectral_centroid_var      0
spectral_bandwidth_mean    0
spectral_bandwidth_var     0
rolloff_mean               0
rolloff_var                0
zero_crossing_rate_mean    0
zero_crossing_rate_var     0
harmony_mean               0
harmony_var                0
perceptr_mean              0
perceptr_var               0
tempo                      0
mfcc1_mean                 0
mfcc1_var                  0
mfcc2_mean                 0
mfcc2_var                  0
mfcc3_mean                 0
mfcc3_var                  0
mfcc4_mean                 0
mfcc4_var                  0
mfcc5_mean                 0
mfcc5_var                  0
mfcc6_mean                 0
mfcc6_var                  0
mfcc7_mean                 0
mfcc7_var                  0
mfcc8_mean                 0
mfcc8_var                  0
mfcc9_mean                 0
mfcc9_var                  0
mfcc10_mean                0
mfcc10_var                 0
mfcc11_mean                0
mfcc11_var                 0
mfcc12_mean                0
mfcc12_var                 0
mfcc13_mean                0
mfcc13_var                 0
mfcc14_mean                0
mfcc14_var                 0
mfcc15_mean                0
mfcc15_var                 0
mfcc16_mean                0
mfcc16_var                 0
mfcc17_mean                0
mfcc17_var                 0
mfcc18_mean                0
mfcc18_var                 0
mfcc19_mean                0
mfcc19_var                 0
mfcc20_mean                0
mfcc20_var                 0
label                      0
dtype: int64

#Dropping duplicates

In [ ]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of                filename  length  chroma_stft_mean  chroma_stft_var  rms_mean  \
0     blues.00000.0.wav   66149          0.335406         0.091048  0.130405
1     blues.00000.1.wav   66149          0.343065         0.086147  0.112699
2     blues.00000.2.wav   66149          0.346815         0.092243  0.132003
3     blues.00000.3.wav   66149          0.363639         0.086856  0.132565
4     blues.00000.4.wav   66149          0.335579         0.088129  0.143289
...                 ...     ...               ...              ...       ...
9985   rock.00099.5.wav   66149          0.349126         0.080515  0.050019
9986   rock.00099.6.wav   66149          0.372564         0.082626  0.057897
9987   rock.00099.7.wav   66149          0.347481         0.089019  0.052403
9988   rock.00099.8.wav   66149          0.387527         0.084815  0.066430
9989   rock.00099.9.wav   66149          0.369293         0.086759  0.050524

       rms_var  spectral_centroid_mean  spectral_centroid_var  \
0     0.003521             1773.065032          167541.630869
1     0.001450             1816.693777           90525.690866
2     0.004620             1788.539719          111407.437613
3     0.002448             1655.289045          111952.284517
4     0.001701             1630.656199           79667.267654
...        ...                     ...                    ...
9985  0.000097             1499.083005          164266.886443
9986  0.000088             1847.965128          281054.935973
9987  0.000701             1346.157659          662956.246325
9988  0.000320             2084.515327          203891.039161
9989  0.000067             1634.330126          411429.169769

      spectral_bandwidth_mean  spectral_bandwidth_var  ...  mfcc16_var  \
0                 1972.744388           117335.771563  ...   39.687145
1                 2010.051501            65671.875673  ...   64.748276
2                 2084.565132            75124.921716  ...   67.336563
3                 1960.039988            82913.639269  ...   47.739452
4                 1948.503884            60204.020268  ...   30.336359
...                       ...                     ...  ...         ...
9985              1718.707215            85931.574523  ...   42.485981
9986              1906.468492            99727.037054  ...   32.415203
9987              1561.859087           138762.841945  ...   78.228149
9988              2018.366254            22860.992562  ...   28.323744
9989              1867.422378           119722.211518  ...   38.801735

      mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  \
0       -3.241280   36.488243     0.722209   38.099152    -5.050335
1       -6.055294   40.677654     0.159015   51.264091    -2.837699
2       -1.768610   28.348579     2.378768   45.717648    -1.938424
3       -3.841155   28.337118     1.218588   34.770935    -3.580352
4        0.664582   45.880913     1.689446   51.363583    -3.392489
...           ...         ...          ...         ...          ...
9985    -9.094270   38.326839    -4.246976   31.049839    -5.625813
9986   -12.375726   66.418587    -3.081278   54.414265   -11.960546
9987    -2.524483   21.778994     4.809936   25.980829     1.775686
9988    -5.363541   17.209942     6.462601   21.442928     2.354765
9989   -11.598399   58.983097    -0.178517   55.761299    -6.903252

      mfcc19_var  mfcc20_mean  mfcc20_var  label
0      33.618073    -0.243027   43.771767  blues
1      97.030830     5.784063   59.943081  blues
2      53.050835     2.517375   33.105122  blues
3      50.836224     3.630866   32.023678  blues
4      26.738789     0.536961   29.146694  blues
...          ...          ...         ...    ...
9985   48.804092     1.818823   38.966969   rock
9986   63.452255     0.428857   18.697033   rock
9987   48.582378    -0.299545   41.586990   rock
9988   24.843613     0.675824   12.787750   rock
9989   39.485901    -3.412534   31.727489   rock

[9990 rows x 60 columns]>

#Checking for null values

In [ ]:
print(df.isnull().sum())

In [ ]:
df['label'].nunique()

10

In [ ]:
df['label'].unique()

array(['blues', 'classical', 'country', 'disco', 'hiphop', 'jazz',
       'metal', 'pop', 'reggae', 'rock'], dtype=object)

#Converting categorical label values to numerical values

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder= LabelEncoder()
df['label'] = labelencoder.fit_transform(df['label'])
print(df['label'])

0       0
1       0
2       0
3       0
4       0
       ..
9985    9
9986    9
9987    9
9988    9
9989    9
Name: label, Length: 9990, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder= LabelEncoder()
df['label'] = labelencoder.fit_transform(df['label'])

In [ ]:
print(df['label'])

0       0
1       0
2       0
3       0
4       0
       ..
9985    9
9986    9
9987    9
9988    9
9989    9
Name: label, Length: 9990, dtype: int64

In [ ]:
df.drop(['filename'],axis=1,inplace=True)
df.head()

,length,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,spectral_centroid_mean,spectral_centroid_var,spectral_bandwidth_mean,spectral_bandwidth_var,rolloff_mean,...,mfcc16_var,mfcc17_mean,mfcc17_var,mfcc18_mean,mfcc18_var,mfcc19_mean,mfcc19_var,mfcc20_mean,mfcc20_var,label
0,66149,0.335406,0.091048,0.130405,0.003521,1773.065032,167541.630869,1972.744388,117335.771563,3714.560359,...,39.687145,-3.241280,36.488243,0.722209,38.099152,-5.050335,33.618073,-0.243027,43.771767,0
1,66149,0.343065,0.086147,0.112699,0.001450,1816.693777,90525.690866,2010.051501,65671.875673,3869.682242,...,64.748276,-6.055294,40.677654,0.159015,51.264091,-2.837699,97.030830,5.784063,59.943081,0
2,66149,0.346815,0.092243,0.132003,0.004620,1788.539719,111407.437613,2084.565132,75124.921716,3997.639160,...,67.336563,-1.768610,28.348579,2.378768,45.717648,-1.938424,53.050835,2.517375,33.105122,0
3,66149,0.363639,0.086856,0.132565,0.002448,1655.289045,111952.284517,1960.039988,82913.639269,3568.300218,...,47.739452,-3.841155,28.337118,1.218588,34.770935,-3.580352,50.836224,3.630866,32.023678,0
4,66149,0.335579,0.088129,0.143289,0.001701,1630.656199,79667.267654,1948.503884,60204.020268,3469.992864,...,30.336359,0.664582,45.880913,1.689446,51.363583,-3.392489,26.738789,0.536961,29.146694,0

*italicized text*#Doing PCA

In [ ]:
from sklearn.decomposition import PCA
from sklearn.decomposition import PCA
pca = PCA(whiten=True)
pca.fit(df)
variance = pd.DataFrame(pca.explained_variance_ratio_)
np.cumsum(pca.explained_variance_ratio_)

array([0.97003307, 0.99920137, 0.99999685, 0.99999906, 0.99999992,
       0.99999994, 0.99999997, 0.99999998, 0.99999998, 0.99999999,
       0.99999999, 0.99999999, 0.99999999, 0.99999999, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        ])

In [ ]:
from sklearn.decomposition import PCA
from sklearn.decomposition import PCA
pca = PCA(whiten=True)
pca.fit(df)
variance = pd.DataFrame(pca.explained_variance_ratio_)
np.cumsum(pca.explained_variance_ratio_)
pca = PCA(n_components=25,whiten=True)
pca = pca.fit(df)
dataPCA = pd.DataFrame(pca.transform(df))

In [ ]:
X= dataPCA

In [ ]:
print(X)

            0         1         2         3         4         5         6   \
0    -0.384945 -0.448064  0.593063 -0.005834 -0.135440  0.760913  0.431983
1    -0.657655 -0.371607  0.001288  0.062999 -0.080034  0.525601  0.023177
2    -0.579004 -0.397729  0.046037  0.729340  0.336703  0.816512 -0.539265
3    -0.495539 -0.508474  0.008751  0.225841 -0.215638  0.495360 -0.649567
4    -0.698848 -0.357525 -0.033522  0.176040 -0.346402  0.753950 -0.272179
...        ...       ...       ...       ...       ...       ...       ...
9985 -0.534381 -0.255316  0.257667  0.063323 -0.846845  0.113792 -0.590286
9986 -0.311507 -0.104438  0.174411 -0.585143 -0.758746 -0.063262 -0.529257
9987  0.655640  0.072245 -0.846228  6.536782  0.993021  0.931798  0.702187
9988 -0.753645  0.202332 -0.554363  0.628409  0.076124  0.321115 -0.587811
9989 -0.071652  0.075031  0.210195 -0.191008 -1.030733 -1.042455 -1.030936

            7         8         9   ...        15        16        17  \
0    -0.073197  0.349439 -0.306037  ...  1.138611 -0.763863 -0.037782
1    -0.318685  0.448896 -0.269826  ... -0.552947 -0.111085 -0.103947
2    -0.736752  0.322227 -0.498719  ... -0.261226 -0.055239 -0.380531
3    -0.504137  0.879435 -0.239968  ...  0.526364  0.005320 -0.067312
4    -0.528764  0.100362 -0.120108  ...  0.618407 -0.296727 -0.285970
...        ...       ...       ...  ...       ...       ...       ...
9985 -0.099430 -0.338230 -0.283796  ... -0.009100  0.546378 -0.071315
9986  0.194474  0.344388 -0.306864  ... -0.207615  0.149194 -1.315831
9987  1.220146 -2.680263 -0.078734  ...  0.471197  0.417040  0.061996
9988  0.267353 -0.391602 -0.850656  ... -0.398021 -0.184653 -0.160637
9989 -0.751348 -0.594302 -0.598792  ... -0.370990  0.440472  3.317393

            18        19        20        21        22        23        24
0    -0.907449 -0.406639  0.864780  0.519285  0.139580  0.520190 -0.079071
1     0.037892 -0.056150  0.085354  0.402684 -0.862807  0.763437  1.522797
2    -1.167410 -0.480750 -1.426272  0.385103 -0.221881  0.446034  1.207413
3    -0.241178  0.485782 -0.469617 -0.019208 -0.438555  0.050356  0.258340
4    -0.985962 -0.815887 -0.577465 -0.289825  0.264628  0.148305 -0.157224
...        ...       ...       ...       ...       ...       ...       ...
9985 -0.063453  0.809301  0.053473  0.278391 -0.190421 -0.266362  1.150678
9986 -0.275945 -0.791624  1.658884 -0.416801 -0.554189 -0.472616  0.068055
9987  0.403761  2.013899  1.855262  0.752904 -0.670361  1.684976 -0.149753
9988 -0.928372  1.802712  1.168049 -0.060784 -0.052270  0.158974  0.399359
9989 -0.597757 -1.255305  1.079593 -0.358359  0.332923  0.150717 -0.221146

[9990 rows x 25 columns]

#Split data for training and testing

In [ ]:
y = df.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

#Decision tree

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(accuracy_score(y_pred, y_test)*100)

48.8988988988989

#Random Forest

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf= RandomForestClassifier(n_estimators=100,random_state=0)
rf.fit(X_train,y_train)

RandomForestClassifier(random_state=0)

In [ ]:
y_pred= rf.predict(X_test)
print("Accuracy Score RandomForest: ",accuracy_score(y_test,y_pred))

Accuracy Score RandomForest:  0.6921921921921922

#KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=5)  #it's changing based on n_neighbors value
classifier.fit(X_train, y_train)

In [ ]:
y_pred= classifier.predict(X_test)

In [ ]:
print("Accuracy score: ", accuracy_score(y_pred, y_test)*100)

Accuracy score:  60.96096096096096

#Naive bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb_model = GaussianNB()
nb_model = nb_model.fit(X_train,y_train)
y_pred = nb_model.predict(X_test)
print(accuracy_score(y_pred, y_test)*100)

38.93893893893894

#XG Booster

In [ ]:
from xgboost import XGBClassifier

In [ ]:
from xgboost import XGBClassifier
model = XGBClassifier(n_estimators=1000)
model.fit(X_train,y_train,eval_metric='merror')
y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)
target_names = sorted(set(y))

print(f'Training accuracy: {accuracy_score(y_train,y_pred_train)}')
#print(f'Training:\n {classification_report(y_train, y_pred_train, labels=target_names)}')
print(f'Testing accuracy: {accuracy_score(y_test,y_pred_test)}')
#print(f'Testing:\n {classification_report(y_test, y_pred_test, labels=target_names)}')

/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:885: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=1000, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [ ]:
y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)
target_names = sorted(set(y))

print(f'Training accuracy: {accuracy_score(y_train,y_pred_train)}')
#print(f'Training:\n {classification_report(y_train, y_pred_train, labels=target_names)}')
print(f'Testing accuracy: {accuracy_score(y_test,y_pred_test)}')
#print(f'Testing:\n {classification_report(y_test, y_pred_test, labels=target_names)}')

Training accuracy: 0.9998748748748749
Testing accuracy: 0.7267267267267268

#Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy Score: ",accuracy_score(y_pred,y_test))

Accuracy Score:  0.549049049049049

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn import metrics

In [ ]:
unique_labels, counts = np.unique(y_test, return_counts=True)

# Print the counts for each unique label
for label, count in zip(unique_labels, counts):
    print(f"Label {label}: {count} occurrences")

Label 0: 20 occurrences
Label 1: 13 occurrences
Label 2: 27 occurrences
Label 3: 21 occurrences
Label 4: 15 occurrences
Label 5: 22 occurrences
Label 6: 25 occurrences
Label 7: 13 occurrences
Label 8: 23 occurrences
Label 9: 21 occurrences

In [ ]:
y_pred= LogReg.predict(X_test)
print("Accuracy Score: ",metrics.accuracy_score(y_pred,y_test))
print(metrics.confusion_matrix(y_test,y_pred))

Accuracy Score:  0.835
[[19  0  1  0  0  0  0  0  0  0]
 [ 0 13  0  0  0  0  0  0  0  0]
 [ 1  0 22  4  0  0  0  0  0  0]
 [ 1  2  0 14  4  0  0  0  0  0]
 [ 0  0  0  2 13  0  0  0  0  0]
 [ 0  0  0  1  1 20  0  0  0  0]
 [ 0  0  0  0  2  0 22  0  0  1]
 [ 0  0  0  0  0  2  0 11  0  0]
 [ 0  0  0  0  0  0  0  2 16  5]
 [ 0  0  0  0  0  0  0  0  4 17]]

#Support vector machine

In [ ]:
from sklearn.svm import SVC
svm_model = SVC()
svm_model = svm_model.fit(X_train,y_train)
y_pred = svm_model.predict(X_test)
print(accuracy_score(y_pred, y_test)*100)

66.96696696696696

#CNN

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/ML Project/genres/features_3_sec.csv")
df.head()

In [ ]:
class_encod=df.iloc[:,-1]
converter=LabelEncoder()
y=converter.fit_transform(class_encod)
y

array([0, 0, 0, ..., 9, 9, 9])

In [ ]:
#Drop the column filename as it is no longer required for training
df=df.drop(labels="filename",axis=1)

In [ ]:
#scaling
from sklearn.preprocessing import StandardScaler
fit=StandardScaler()
X=fit.fit_transform(np.array(df.iloc[:,:-1],dtype=float))

In [ ]:
# splitting 70% data into training set and the remaining 30% to test set
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [ ]:
def train_model(model,epochs,optimizer):
    batch_size=256
    model.compile(optimizer=optimizer,loss='sparse_categorical_crossentropy',metrics='accuracy')
    return model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=epochs,batch_size=batch_size)

In [ ]:
def Validation_plot(history):
    print("Validation Accuracy",max(history.history["val_accuracy"]))

In [ ]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(X.shape[1],)),
    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(512,activation='relu'),
    keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(256,activation='relu'),
    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(32,activation='relu'),
    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(10,activation='softmax'),
])

optimizer = tf.keras.optimizers.Adam(learning_rate=0.000146)
model.compile(optimizer=optimizer,
             loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])
model.summary()
model_history=train_model(model=model,epochs=600,optimizer='adam')

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 flatten_1 (Flatten)         (None, 58)                0

 dropout_6 (Dropout)         (None, 58)                0

 dense_6 (Dense)             (None, 512)               30208

 dropout_7 (Dropout)         (None, 512)               0

 dense_7 (Dense)             (None, 256)               131328

 dropout_8 (Dropout)         (None, 256)               0

 dense_8 (Dense)             (None, 128)               32896

 dropout_9 (Dropout)         (None, 128)               0

 dense_9 (Dense)             (None, 64)                8256

 dropout_10 (Dropout)        (None, 64)                0

 dense_10 (Dense)            (None, 32)                2080

 dropout_11 (Dropout)        (None, 32)                0

 dense_11 (Dense)            (None, 10)                330

=================================================================
Total params: 205098 (801.16 KB)
Trainable params: 205098 (801.16 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/600
28/28 [==============================] - 2s 37ms/step - loss: 2.0801 - accuracy: 0.2329 - val_loss: 1.7106 - val_accuracy: 0.3774
Epoch 2/600
28/28 [==============================] - 1s 29ms/step - loss: 1.7243 - accuracy: 0.3784 - val_loss: 1.4243 - val_accuracy: 0.4968
Epoch 3/600
28/28 [==============================] - 1s 27ms/step - loss: 1.4839 - accuracy: 0.4725 - val_loss: 1.1682 - val_accuracy: 0.6143
Epoch 4/600
28/28 [==============================] - 1s 29ms/step - loss: 1.3659 - accuracy: 0.5272 - val_loss: 1.0487 - val_accuracy: 0.6630
Epoch 5/600
28/28 [==============================] - 1s 30ms/step - loss: 1.2600 - accuracy: 0.5673 - val_loss: 0.9568 - val_accuracy: 0.6877
Epoch 6/600
28/28 [==============================] - 1s 28ms/step - loss: 1.1766 - accuracy: 0.6002 - val_loss: 0.9034 - val_accuracy: 0.7167
Epoch 7/600
28/28 [==============================] - 1s 27ms/step - loss: 1.1212 - accuracy: 0.6202 - val_loss: 0.8290 - val_accuracy: 0.7277
Epoch 8/600
28/28 [==============================] - 1s 27ms/step - loss: 1.0800 - accuracy: 0.6395 - val_loss: 0.8139 - val_accuracy: 0.7337
Epoch 9/600
28/28 [==============================] - 1s 29ms/step - loss: 1.0545 - accuracy: 0.6501 - val_loss: 0.7787 - val_accuracy: 0.7494
Epoch 10/600
28/28 [==============================] - 1s 19ms/step - loss: 1.0039 - accuracy: 0.6680 - val_loss: 0.7309 - val_accuracy: 0.7578
Epoch 11/600
28/28 [==============================] - 1s 18ms/step - loss: 0.9887 - accuracy: 0.6660 - val_loss: 0.7272 - val_accuracy: 0.7644
Epoch 12/600
28/28 [==============================] - 0s 17ms/step - loss: 0.9465 - accuracy: 0.6871 - val_loss: 0.7065 - val_accuracy: 0.7654
Epoch 13/600
28/28 [==============================] - 0s 18ms/step - loss: 0.9182 - accuracy: 0.6928 - val_loss: 0.6754 - val_accuracy: 0.7784
Epoch 14/600
28/28 [==============================] - 1s 18ms/step - loss: 0.9040 - accuracy: 0.7026 - val_loss: 0.6416 - val_accuracy: 0.7901
Epoch 15/600
28/28 [==============================] - 1s 18ms/step - loss: 0.8732 - accuracy: 0.7113 - val_loss: 0.6191 - val_accuracy: 0.7965
Epoch 16/600
28/28 [==============================] - 1s 18ms/step - loss: 0.8620 - accuracy: 0.7131 - val_loss: 0.6243 - val_accuracy: 0.7991
Epoch 17/600
28/28 [==============================] - 0s 18ms/step - loss: 0.8326 - accuracy: 0.7243 - val_loss: 0.6162 - val_accuracy: 0.7925
Epoch 18/600
28/28 [==============================] - 0s 17ms/step - loss: 0.8171 - accuracy: 0.7283 - val_loss: 0.5881 - val_accuracy: 0.8101
Epoch 19/600
28/28 [==============================] - 0s 18ms/step - loss: 0.8241 - accuracy: 0.7314 - val_loss: 0.5737 - val_accuracy: 0.8125
Epoch 20/600
28/28 [==============================] - 0s 17ms/step - loss: 0.7882 - accuracy: 0.7409 - val_loss: 0.5541 - val_accuracy: 0.8182
Epoch 21/600
28/28 [==============================] - 1s 18ms/step - loss: 0.7802 - accuracy: 0.7476 - val_loss: 0.5406 - val_accuracy: 0.8212
Epoch 22/600
28/28 [==============================] - 0s 17ms/step - loss: 0.7746 - accuracy: 0.7456 - val_loss: 0.5228 - val_accuracy: 0.8328
Epoch 23/600
28/28 [==============================] - 0s 18ms/step - loss: 0.7398 - accuracy: 0.7595 - val_loss: 0.5122 - val_accuracy: 0.8355
Epoch 24/600
28/28 [==============================] - 0s 18ms/step - loss: 0.7408 - accuracy: 0.7575 - val_loss: 0.5088 - val_accuracy: 0.8365
Epoch 25/600
28/28 [==============================] - 0s 17ms/step - loss: 0.7364 - accuracy: 0.7623 - val_loss: 0.4970 - val_accuracy: 0.8358
Epoch 26/600
28/28 [==============================] - 0s 17ms/step - loss: 0.6977 - accuracy: 0.7651 - val_loss: 0.4937 - val_accuracy: 0.8452
Epoch 27/600
28/28 [==============================] - 0s 18ms/step - loss: 0.6912 - accuracy: 0.7722 - val_loss: 0.4604 - val_accuracy: 0.8505
Epoch 28/600
28/28 [==============================] - 0s 17ms/step - loss: 0.6820 - accuracy: 0.7736 - val_loss: 0.4528 - val_accuracy: 0.8522
Epoch 29/600
28/28 [==============================] - 0s 17ms/step - loss: 0.6852 - accuracy: 0.7758 - val_loss: 0.4549 - val_accuracy: 0.8575
Epoch 30/600
28/28 [==============================] - 1s 26ms/step - loss: 0.6799 - accuracy: 0.7771 - val_loss: 0.4575 - val_accuracy: 0.8545
Epoch 31/600
28/28 [==============================] - 1s 31ms/step - loss: 0.6612 - accuracy: 0.7856 - val_loss: 0.4540 - val_accuracy: 0.8559
Epoch 32/600
28/28 [==============================] - 1s 29ms/step - loss: 0.6479 - accuracy: 0.7908 - val_loss: 0.4350 - val_accuracy: 0.8595
Epoch 33/600
28/28 [==============================] - 1s 28ms/step - loss: 0.6365 - accuracy: 0.7982 - val_loss: 0.4292 - val_accuracy: 0.8642
Epoch 34/600
28/28 [==============================] - 1s 26ms/step - loss: 0.6331 - accuracy: 0.7962 - val_loss: 0.4264 - val_accuracy: 0.8619
Epoch 35/600
28/28 [==============================] - 1s 28ms/step - loss: 0.6402 - accuracy: 0.7964 - val_loss: 0.4180 - val_accuracy: 0.8689
Epoch 36/600
28/28 [==============================] - 1s 27ms/step - loss: 0.5979 - accuracy: 0.8094 - val_loss: 0.4039 - val_accuracy: 0.8699
Epoch 37/600
28/28 [==============================] - 1s 29ms/step - loss: 0.5976 - accuracy: 0.8071 - val_loss: 0.3950 - val_accuracy: 0.8765
Epoch 38/600
28/28 [==============================] - 1s 29ms/step - loss: 0.6103 - accuracy: 0.8067 - val_loss: 0.4060 - val_accuracy: 0.8712
Epoch 39/600
28/28 [==============================] - 1s 25ms/step - loss: 0.5938 - accuracy: 0.8110 - val_loss: 0.3920 - val_accuracy: 0.8702
Epoch 40/600
28/28 [==============================] - 0s 17ms/step - loss: 0.6008 - accuracy: 0.8087 - val_loss: 0.3896 - val_accuracy: 0.8782
Epoch 41/600
28/28 [==============================] - 0s 18ms/step - loss: 0.5703 - accuracy: 0.8185 - val_loss: 0.3727 - val_accuracy: 0.8819
Epoch 42/600
28/28 [==============================] - 0s 17ms/step - loss: 0.5741 - accuracy: 0.8130 - val_loss: 0.3784 - val_accuracy: 0.8842
Epoch 43/600
28/28 [==============================] - 1s 18ms/step - loss: 0.5663 - accuracy: 0.8141 - val_loss: 0.3751 - val_accuracy: 0.8849
Epoch 44/600
28/28 [==============================] - 0s 18ms/step - loss: 0.5574 - accuracy: 0.8225 - val_loss: 0.3929 - val_accuracy: 0.8705
Epoch 45/600
28/28 [==============================] - 1s 19ms/step - loss: 0.5718 - accuracy: 0.8185 - val_loss: 0.3871 - val_accuracy: 0.8772
Epoch 46/600
28/28 [==============================] - 0s 17ms/step - loss: 0.5666 - accuracy: 0.8237 - val_loss: 0.3788 - val_accuracy: 0.8829
Epoch 47/600
28/28 [==============================] - 1s 18ms/step - loss: 0.5342 - accuracy: 0.8305 - val_loss: 0.3632 - val_accuracy: 0.8859
Epoch 48/600
28/28 [==============================] - 0s 17ms/step - loss: 0.5462 - accuracy: 0.8283 - val_loss: 0.3565 - val_accuracy: 0.8952
Epoch 49/600
28/28 [==============================] - 1s 18ms/step - loss: 0.5402 - accuracy: 0.8255 - val_loss: 0.3564 - val_accuracy: 0.8902
Epoch 50/600
28/28 [==============================] - 0s 18ms/step - loss: 0.5237 - accuracy: 0.8383 - val_loss: 0.3650 - val_accuracy: 0.8892
Epoch 51/600
28/28 [==============================] - 1s 18ms/step - loss: 0.5111 - accuracy: 0.8394 - val_loss: 0.3469 - val_accuracy: 0.8922
Epoch 52/600
28/28 [==============================] - 1s 18ms/step - loss: 0.5080 - accuracy: 0.8413 - val_loss: 0.3590 - val_accuracy: 0.8879
Epoch 53/600
28/28 [==============================] - 1s 18ms/step - loss: 0.4913 - accuracy: 0.8441 - val_loss: 0.3368 - val_accuracy: 0.8972
Epoch 54/600
28/28 [==============================] - 0s 18ms/step - loss: 0.5106 - accuracy: 0.8380 - val_loss: 0.3527 - val_accuracy: 0.8922
Epoch 55/600
28/28 [==============================] - 0s 18ms/step - loss: 0.5097 - accuracy: 0.8355 - val_loss: 0.3531 - val_accuracy: 0.8926
Epoch 56/600
28/28 [==============================] - 0s 17ms/step - loss: 0.4987 - accuracy: 0.8401 - val_loss: 0.3516 - val_accuracy: 0.8932
Epoch 57/600
28/28 [==============================] - 1s 18ms/step - loss: 0.4835 - accuracy: 0.8447 - val_loss: 0.3493 - val_accuracy: 0.8962
Epoch 58/600
28/28 [==============================] - 0s 17ms/step - loss: 0.4751 - accuracy: 0.8510 - val_loss: 0.3634 - val_accuracy: 0.8832
Epoch 59/600
28/28 [==============================] - 1s 23ms/step - loss: 0.5086 - accuracy: 0.8450 - val_loss: 0.3543 - val_accuracy: 0.8912
Epoch 60/600
28/28 [==============================] - 1s 27ms/step - loss: 0.4767 - accuracy: 0.8513 - val_loss: 0.3314 - val_accuracy: 0.8989
Epoch 61/600
28/28 [==============================] - 1s 26ms/step - loss: 0.4792 - accuracy: 0.8468 - val_loss: 0.3192 - val_accuracy: 0.9032
Epoch 62/600
28/28 [==============================] - 1s 30ms/step - loss: 0.4716 - accuracy: 0.8498 - val_loss: 0.3197 - val_accuracy: 0.9046
Epoch 63/600
28/28 [==============================] - 1s 28ms/step - loss: 0.4499 - accuracy: 0.8551 - val_loss: 0.3201 - val_accuracy: 0.9036
Epoch 64/600
28/28 [==============================] - 1s 29ms/step - loss: 0.4679 - accuracy: 0.8540 - val_loss: 0.3246 - val_accuracy: 0.8996
Epoch 65/600
28/28 [==============================] - 1s 25ms/step - loss: 0.4508 - accuracy: 0.8547 - val_loss: 0.3171 - val_accuracy: 0.9002
Epoch 66/600
28/28 [==============================] - 1s 29ms/step - loss: 0.4678 - accuracy: 0.8517 - val_loss: 0.3156 - val_accuracy: 0.9049
Epoch 67/600
28/28 [==============================] - 1s 29ms/step - loss: 0.4420 - accuracy: 0.8630 - val_loss: 0.3200 - val_accuracy: 0.9012
Epoch 68/600
28/28 [==============================] - 1s 29ms/step - loss: 0.4549 - accuracy: 0.8601 - val_loss: 0.3033 - val_accuracy: 0.9079
Epoch 69/600
28/28 [==============================] - 1s 20ms/step - loss: 0.4383 - accuracy: 0.8604 - val_loss: 0.3168 - val_accuracy: 0.9052
Epoch 70/600
28/28 [==============================] - 1s 18ms/step - loss: 0.4374 - accuracy: 0.8619 - val_loss: 0.3080 - val_accuracy: 0.9029
Epoch 71/600
28/28 [==============================] - 1s 18ms/step - loss: 0.4186 - accuracy: 0.8659 - val_loss: 0.3047 - val_accuracy: 0.9062
Epoch 72/600
28/28 [==============================] - 0s 17ms/step - loss: 0.4159 - accuracy: 0.8689 - val_loss: 0.2938 - val_accuracy: 0.9076
Epoch 73/600
28/28 [==============================] - 1s 18ms/step - loss: 0.4331 - accuracy: 0.8662 - val_loss: 0.3026 - val_accuracy: 0.9112
Epoch 74/600
28/28 [==============================] - 0s 18ms/step - loss: 0.4167 - accuracy: 0.8706 - val_loss: 0.2921 - val_accuracy: 0.9096
Epoch 75/600
28/28 [==============================] - 1s 18ms/step - loss: 0.4292 - accuracy: 0.8666 - val_loss: 0.3002 - val_accuracy: 0.9056
Epoch 76/600
28/28 [==============================] - 1s 18ms/step - loss: 0.4135 - accuracy: 0.8690 - val_loss: 0.2932 - val_accuracy: 0.9119
Epoch 77/600
28/28 [==============================] - 1s 18ms/step - loss: 0.4255 - accuracy: 0.8656 - val_loss: 0.3064 - val_accuracy: 0.9102
Epoch 78/600
28/28 [==============================] - 1s 18ms/step - loss: 0.4197 - accuracy: 0.8690 - val_loss: 0.3141 - val_accuracy: 0.9082
Epoch 79/600
28/28 [==============================] - 1s 19ms/step - loss: 0.4160 - accuracy: 0.8677 - val_loss: 0.2942 - val_accuracy: 0.9109
Epoch 80/600
28/28 [==============================] - 0s 18ms/step - loss: 0.4319 - accuracy: 0.8616 - val_loss: 0.3065 - val_accuracy: 0.9039
Epoch 81/600
28/28 [==============================] - 1s 19ms/step - loss: 0.4173 - accuracy: 0.8680 - val_loss: 0.3068 - val_accuracy: 0.9072
Epoch 82/600
28/28 [==============================] - 1s 18ms/step - loss: 0.4158 - accuracy: 0.8717 - val_loss: 0.2917 - val_accuracy: 0.9072
Epoch 83/600
28/28 [==============================] - 1s 18ms/step - loss: 0.4085 - accuracy: 0.8723 - val_loss: 0.3058 - val_accuracy: 0.9026
Epoch 84/600
28/28 [==============================] - 1s 18ms/step - loss: 0.3951 - accuracy: 0.8787 - val_loss: 0.3019 - val_accuracy: 0.9109
Epoch 85/600
28/28 [==============================] - 1s 19ms/step - loss: 0.4026 - accuracy: 0.8700 - val_loss: 0.2941 - val_accuracy: 0.9166
Epoch 86/600
28/28 [==============================] - 0s 18ms/step - loss: 0.3885 - accuracy: 0.8789 - val_loss: 0.2947 - val_accuracy: 0.9092
Epoch 87/600
28/28 [==============================] - 1s 18ms/step - loss: 0.3877 - accuracy: 0.8760 - val_loss: 0.2901 - val_accuracy: 0.9116
Epoch 88/600
28/28 [==============================] - 1s 19ms/step - loss: 0.3855 - accuracy: 0.8796 - val_loss: 0.3196 - val_accuracy: 0.9066
Epoch 89/600
28/28 [==============================] - 1s 29ms/step - loss: 0.3883 - accuracy: 0.8760 - val_loss: 0.2965 - val_accuracy: 0.9099
Epoch 90/600
28/28 [==============================] - 1s 27ms/step - loss: 0.3806 - accuracy: 0.8836 - val_loss: 0.3032 - val_accuracy: 0.9069
Epoch 91/600
28/28 [==============================] - 1s 29ms/step - loss: 0.3996 - accuracy: 0.8694 - val_loss: 0.2878 - val_accuracy: 0.9139
Epoch 92/600
28/28 [==============================] - 1s 26ms/step - loss: 0.4000 - accuracy: 0.8760 - val_loss: 0.2773 - val_accuracy: 0.9183
Epoch 93/600
28/28 [==============================] - 1s 27ms/step - loss: 0.4036 - accuracy: 0.8726 - val_loss: 0.2885 - val_accuracy: 0.9126
Epoch 94/600
28/28 [==============================] - 1s 27ms/step - loss: 0.3586 - accuracy: 0.8862 - val_loss: 0.2783 - val_accuracy: 0.9162
Epoch 95/600
28/28 [==============================] - 1s 27ms/step - loss: 0.3606 - accuracy: 0.8873 - val_loss: 0.2881 - val_accuracy: 0.9146
Epoch 96/600
28/28 [==============================] - 1s 29ms/step - loss: 0.3645 - accuracy: 0.8875 - val_loss: 0.2782 - val_accuracy: 0.9156
Epoch 97/600
28/28 [==============================] - 1s 29ms/step - loss: 0.3667 - accuracy: 0.8846 - val_loss: 0.3019 - val_accuracy: 0.9099
Epoch 98/600
28/28 [==============================] - 1s 25ms/step - loss: 0.3571 - accuracy: 0.8866 - val_loss: 0.2849 - val_accuracy: 0.9183
Epoch 99/600
28/28 [==============================] - 0s 17ms/step - loss: 0.3673 - accuracy: 0.8846 - val_loss: 0.2921 - val_accuracy: 0.9119
Epoch 100/600
28/28 [==============================] - 1s 18ms/step - loss: 0.3758 - accuracy: 0.8810 - val_loss: 0.2989 - val_accuracy: 0.9129
Epoch 101/600
28/28 [==============================] - 1s 19ms/step - loss: 0.3817 - accuracy: 0.8809 - val_loss: 0.2919 - val_accuracy: 0.9166
Epoch 102/600
28/28 [==============================] - 1s 18ms/step - loss: 0.3677 - accuracy: 0.8812 - val_loss: 0.2869 - val_accuracy: 0.9179
Epoch 103/600
28/28 [==============================] - 1s 18ms/step - loss: 0.3654 - accuracy: 0.8889 - val_loss: 0.2784 - val_accuracy: 0.9186
Epoch 104/600
28/28 [==============================] - 1s 19ms/step - loss: 0.3577 - accuracy: 0.8866 - val_loss: 0.2848 - val_accuracy: 0.9179
Epoch 105/600
28/28 [==============================] - 1s 18ms/step - loss: 0.3503 - accuracy: 0.8913 - val_loss: 0.3028 - val_accuracy: 0.9099
Epoch 106/600
28/28 [==============================] - 1s 19ms/step - loss: 0.3409 - accuracy: 0.8913 - val_loss: 0.2864 - val_accuracy: 0.9129
Epoch 107/600
28/28 [==============================] - 0s 17ms/step - loss: 0.3562 - accuracy: 0.8895 - val_loss: 0.2820 - val_accuracy: 0.9146
Epoch 108/600
28/28 [==============================] - 0s 18ms/step - loss: 0.3608 - accuracy: 0.8899 - val_loss: 0.2946 - val_accuracy: 0.9109
Epoch 109/600
28/28 [==============================] - 0s 18ms/step - loss: 0.3631 - accuracy: 0.8879 - val_loss: 0.2952 - val_accuracy: 0.9099
Epoch 110/600
28/28 [==============================] - 1s 18ms/step - loss: 0.3626 - accuracy: 0.8886 - val_loss: 0.2882 - val_accuracy: 0.9146
Epoch 111/600
28/28 [==============================] - 0s 17ms/step - loss: 0.3453 - accuracy: 0.8905 - val_loss: 0.2959 - val_accuracy: 0.9076
Epoch 112/600
28/28 [==============================] - 1s 18ms/step - loss: 0.3423 - accuracy: 0.8877 - val_loss: 0.2829 - val_accuracy: 0.9152
Epoch 113/600
28/28 [==============================] - 0s 18ms/step - loss: 0.3531 - accuracy: 0.8912 - val_loss: 0.2801 - val_accuracy: 0.9122
Epoch 114/600
28/28 [==============================] - 1s 18ms/step - loss: 0.3562 - accuracy: 0.8853 - val_loss: 0.2809 - val_accuracy: 0.9206
Epoch 115/600
28/28 [==============================] - 1s 18ms/step - loss: 0.3467 - accuracy: 0.8968 - val_loss: 0.2780 - val_accuracy: 0.9169
Epoch 116/600
28/28 [==============================] - 1s 19ms/step - loss: 0.3515 - accuracy: 0.8896 - val_loss: 0.2614 - val_accuracy: 0.9229
Epoch 117/600
28/28 [==============================] - 1s 19ms/step - loss: 0.3510 - accuracy: 0.8940 - val_loss: 0.2674 - val_accuracy: 0.9166
Epoch 118/600
28/28 [==============================] - 1s 24ms/step - loss: 0.3202 - accuracy: 0.8975 - val_loss: 0.2587 - val_accuracy: 0.9173
Epoch 119/600
28/28 [==============================] - 1s 29ms/step - loss: 0.3352 - accuracy: 0.8989 - val_loss: 0.2802 - val_accuracy: 0.9159
Epoch 120/600
28/28 [==============================] - 1s 29ms/step - loss: 0.3334 - accuracy: 0.8986 - val_loss: 0.2747 - val_accuracy: 0.9176
Epoch 121/600
28/28 [==============================] - 1s 27ms/step - loss: 0.3301 - accuracy: 0.9030 - val_loss: 0.2761 - val_accuracy: 0.9189
Epoch 122/600
28/28 [==============================] - 1s 27ms/step - loss: 0.3364 - accuracy: 0.8978 - val_loss: 0.2628 - val_accuracy: 0.9209
Epoch 123/600
28/28 [==============================] - 1s 29ms/step - loss: 0.3189 - accuracy: 0.9009 - val_loss: 0.2687 - val_accuracy: 0.9239
Epoch 124/600
28/28 [==============================] - 1s 26ms/step - loss: 0.3299 - accuracy: 0.8970 - val_loss: 0.2691 - val_accuracy: 0.9199
Epoch 125/600
28/28 [==============================] - 1s 30ms/step - loss: 0.3347 - accuracy: 0.8949 - val_loss: 0.2651 - val_accuracy: 0.9249
Epoch 126/600
28/28 [==============================] - 1s 27ms/step - loss: 0.3423 - accuracy: 0.8965 - val_loss: 0.2684 - val_accuracy: 0.9226
Epoch 127/600
28/28 [==============================] - 1s 26ms/step - loss: 0.3282 - accuracy: 0.8983 - val_loss: 0.2676 - val_accuracy: 0.9176
Epoch 128/600
28/28 [==============================] - 1s 21ms/step - loss: 0.3085 - accuracy: 0.9045 - val_loss: 0.2549 - val_accuracy: 0.9276
Epoch 129/600
28/28 [==============================] - 1s 19ms/step - loss: 0.3129 - accuracy: 0.8978 - val_loss: 0.2554 - val_accuracy: 0.9253
Epoch 130/600
28/28 [==============================] - 0s 18ms/step - loss: 0.3095 - accuracy: 0.9016 - val_loss: 0.2585 - val_accuracy: 0.9196
Epoch 131/600
28/28 [==============================] - 1s 18ms/step - loss: 0.3007 - accuracy: 0.9053 - val_loss: 0.2560 - val_accuracy: 0.9226
Epoch 132/600

In [ ]:
test_loss,test_acc=model.evaluate(X_test,y_test,batch_size=256)
print("The test loss is ",test_loss)
print("The best accuracy is: ",test_acc*100)

12/12 [==============================] - 0s 7ms/step - loss: 0.2575 - accuracy: 0.9366
The test loss is  0.257521390914917
The best accuracy is:  93.66032481193542

In [ ]:
# The plot dipicts how training and testing data performed
Validation_plot(model_history)

Validation Accuracy 0.9426092505455017